FROM python:3.12-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY . /app/

RUN uv sync --locked

EXPOSE 8000

ENTRYPOINT [
  "uv",
  "run",
  "uvicorn",
  "extraction_review.api:app",
  "--host",
  "0.0.0.0",
  "--port",
  "8000"
]
