FROM python:3.12-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update \
    && apt-get install -y --no-install-recommends tesseract-ocr tesseract-ocr-eng \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app/

RUN uv sync --locked

EXPOSE 8000

ENTRYPOINT ["/app/scripts/start.sh"]
CMD ["uv", "run", "jubeex-sqs-worker"]
